#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server
# Requirments
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# The username scp connects with
# The path to the SSH private key that scp uses

if [ $# -ge 3 ]
then
    if [ $# -eq 3 ]
    then
        # No private key provided
        scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
    else
        # Private key provided
        scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
    fi
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
