#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to respect above requirements

apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
