#!/usr/bin/env bash
# This bash script installs haproxy and configurate both servers

apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\n\nbackend back\n\tbalance roundrobin\n\tserver 32154-web-01 3.233.234.234:80 check\n\tserver 32154-web-02 107.21.40.158:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
