#!/usr/bin/env bash
# A Bash script with the minimum number of commands to automate a fix on Nginx on running, and listening on port 80 of all the server’s active IPv4 IPs

sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart